# Generated by Django 4.2.3 on 2023-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentreg", "0002_student_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
