# Generated by Django 4.2.3 on 2023-07-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0004_alter_module_courses_allowed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'module')},
        ),
    ]
