# Generated by Django 4.2.3 on 2023-08-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studentreg", "0005_alter_registration_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="studentreg.module",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_registrations",
                to="studentreg.student",
            ),
        ),
    ]
